name: Docker Image CI

on:
  push:
    branches: #[ "main" ]
    - '**'
  pull_request:
    branches: #[ "main" ]
    - '**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore ./Bistro/Bistro.sln
    - name: Build
      run: dotnet build ./Bistro/Bistro.sln
    - name: Test with the dotnet CLI
      run: dotnet test ./Bistro/Bistro.sln
      
    #- uses: actions/checkout@v4

    #- name: Run tests
      #run: dotnet test /home/runner/Bistro/Bistro.UnitTest/Bistro.UnitTest.csproj --logger trx

    - if: success()
      name: Build the Docker image
      run: docker build -f ./Bistro/Dockerfile . --file Dockerfile --tag my-image-name:$(date +%s)

    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
         name: artifact:$(date +%s) # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
         path: ./artifacts/

