name: Docker Image CI

on:
  push:
    branches: #[ "main" ]
    - '**'
  pull_request:
    branches: #[ "main" ]
    - '**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Bistro
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test
      
    #- uses: actions/checkout@v4

    #- name: Run tests
      #run: dotnet test /home/runner/Bistro/Bistro.UnitTest/Bistro.UnitTest.csproj --logger trx

    - if: success()
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        # Artifact name
         name: workspace_artifacts # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
         path: ${{ github.workspace }}

